// Code generated by hertz generator.

package main

import (
	handler "simplified-tik-tok/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	// Delete
	apiRouter := r.Group("/douyin")

	r.GetOptions().MaxRequestBodySize = 1 << 30

	apiRouter.GET("/user/", handler.UserInfo)
	// base api
	apiRouter.GET("/ping/", handler.Ping)

	apiRouter.POST("/user/login/", handler.Login)

	apiRouter.POST("/user/register/", handler.Register)

	apiRouter.POST("/publish/action/", handler.PublishAction)

	apiRouter.GET("/publish/list/", handler.PublishList)

	apiRouter.POST("/favorite/action/", handler.FavoriteAction)

	apiRouter.GET("/favorite/list/", handler.FavoriteList)

	apiRouter.POST("/comment/action/", handler.CommentAction)

	apiRouter.GET("/comment/list/", handler.CommentList)

	apiRouter.GET("/feed/", handler.Feed)

	apiRouter.POST("/relation/action/", handler.RelationAction)

	apiRouter.GET("/relation/follow/list/", handler.RelationFollowList)

	apiRouter.GET("/relation/follower/list/", handler.RelationFollowerList)

	apiRouter.GET("/relation/friend/list/", handler.RelationFriendList)

	apiRouter.GET("/play/:name", handler.Play)

	apiRouter.GET("/cover/:name", handler.Cover)

	// 聊天路由
	apiRouter.GET("/message", handler.Message)
	// 聊天消息漫游
	apiRouter.POST("/message/history", handler.MessageHistory)
}
